### ISSUE TITLE
Missing Event Reason code definitions for Door As Switch functionality

### ISSUE THREAD

**Issue by GWustenstein** [uhppoted/uhppoted-dll#1]
There is a 4-door controller in my application, with one of the channels is configured Door-As-Switch.  

The dll, and I suspect other areas of uhppoted, lack defs for the Door-As-Switch event reason codes:  
SWIPE_OPEN = 2
SWIPE_CLOSED = 3

Normal behavior of such a channel is that of a flip-flop:  Swipe triggers the relay to the Door Open state, another swipe resets it to the Door Closed state.  The Push input will 'Open' the channel for the channel's programmed 'open' amount of time, then the channel will revert to 'Closed'.  If such a channel has been swiped 'open' and you assert a Push, the open timer will count down (default is usually 4sec) then the channel will reset to closed.  The functionality is pretty handy for enabling time/task-based door unlocks, turning on/off lights, HVAC, and the like, and you have a log of who dunnit.

-GW

**Comment by uhppoted** [comment]
Event reason codes 2 and 3 are marked _reserved_ in the documentation I have - will update it. 

Can you please run
```
uhppote-cli --debug get-door control <controller> <door>
```
for the door that is configured as _door-as-switch_ and attach the output ?

**Comment by GWustenstein** [comment]
Regarding a run with uhppote-cli; I'll see what I can do, so far, this system is running remotely across town over uhppoted-tunnel, and into its native app and a python script, and my arms are not that long;)

**Comment by uhppoted** [comment]
re. arms. lol ... there's always surgery :-)

The reason for the request is that to confirm there isn't perhaps an undocumented door control mode - the SDK documentation only lists _normally-open_, _normally-closed_ and _controlled_ - no mention whatsoever of _door-as-switch_.

**Comment by GWustenstein** [comment]
In the app, it is enabled as follows:
Tools Tab -> Extended Function -> [Super] -> Configuration -> checkbox for Activate Door As Switch
Once active, the option appears as a drop-down for door configuration.

No description in the manual for the feature, it was explained to be in a (rare) chat session with the vendor in trying to solve the issue of having irregular 'open for business' hours and the rest of the time having access controlled.  BTW, emails sent to uhppote.com appear to bounce these days.

**Comment by uhppoted** [comment]
Thanks! I guess it's either a proprietary feature or controlled by the app.

re. uhppote.com. They are normally quite responsive if you post a question on their Amazon page.

**Comment by GWustenstein** [comment]
Here are all the goodies in my manual...
[Scan2022-10-04_112844.pdf](https://github.com/uhppoted/uhppoted-dll/files/9709668/Scan2022-10-04_112844.pdf)

**Comment by uhppoted** [comment]
And that's a wrap .. pending release

**Comment by GWustenstein** [comment]
Once released, I'll build and push it out to the respective node and beat it about the head and shoulders...

**Comment by uhppoted** [comment]
Closing - released in [v0.8.2](https://github.com/uhppoted/uhppoted-dll/releases/tag/v0.8.2). 

Feel free to reopen it if you need to...
