### ISSUE TITLE
Add support for event listener with callback

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted-dll#11]
Ref. [Example C# Project](https://github.com/uhppoted/uhppoted/discussions/42)

- [x] Go
- [x] C
- [x] C++
- [x] Python
- [x] C#
- [x] CCL

### Notes
1. https://pkg.go.dev/cmd/cgo
2. https://stackoverflow.com/questions/47658347/wait-for-signal-then-continue-execution
3. https://www.gnu.org/software/libc/manual/html_node/Sigsuspend.html
4. https://stackoverflow.com/questions/15992574/how-does-pause-work
5. https://stackoverflow.com/questions/813086/can-i-send-a-ctrl-c-sigint-to-an-application-on-windows
6. https://github.com/matiasinsaurralde/cgo-channels
7. https://stackoverflow.com/questions/177856/how-do-i-trap-ctrlc-sigint-in-a-c-sharp-console-app

**Comment by twystd** [comment]
Initial implementation completed (including [Windows LTSC](https://github.com/uhppoted/uhppoted/discussions/50#discussioncomment-10140201) variant).
