### ISSUE TITLE
Rework for LTSC branch

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted-dll#12]
Ref. https://github.com/uhppoted/uhppoted/discussions/50

Rework all API functions:
- use preallocated memory for strings
- flatten deeply nested _structs_
- rework error as _struct_ with error code and error string
- move err into argument list
- LTSC build directive

Tasks:
- [x] get-devices
- [x] get-device
- [x] set-address
- [x] get-status
- [x] get-time
- [x] set-time
- [x] get-listener
- [x] set-listener
- [x] get-door-control
- [x] set-door-control
- [x] open-door
- [x] get-cards
- [x] get-card
- [x] get-card-by-index
- [x] put-card
- [x] delete-card
- [x] delete-cards
- [x] get-event-index
- [x] set-event-index
- [x] get-event
- [x] record-special-events
- [x] get-time-profile
- [x] set-time-profile
- [x] clear-time-profiles
- [x] add-task
- [x] refresh-tasklist
- [x] clear-tasklist
- [x] set-pc-control
- [x] set-interlock
- [x] activate-keypads
- [x] set-door-passcodes
- [x] restore-default-parameters
- [x] merge back into _main_

## Notes
- [Windows 10 LTSC Program unable to load certain dll's](https://answers.microsoft.com/en-us/windows/forum/all/windows-10-ltsc-program-unable-to-load-certain/1d28f2b6-588e-45b0-b31a-15f6745b46cd)
- [AppLocker CSP](https://learn.microsoft.com/en-us/windows/client-management/mdm/applocker-csp#applicationlaunchrestrictionsgroupingdll)
- [[char* pointer from string in C#](https://stackoverflow.com/questions/1658269/char-pointer-from-string-in-c-sharp)](https://stackoverflow.com/questions/1658269/char-pointer-from-string-in-c-sharp)
- https://learn.microsoft.com/en-us/dotnet/api/system.intptr.op_explicit?view=net-8.0
- https://codereview.stackexchange.com/questions/97186/reading-a-pointer-to-a-string
- https://stackoverflow.com/questions/9175861/how-can-i-convert-an-unmanaged-intptr-type-to-a-c-sharp-string#9175905

**Comment by twystd** [comment]
- Updated `main` branch with preallocated strings à la LTSC
- Reworked error handling to use a `struct`
- Reordered function parameters to follow _in-out-err_ convention

Closing as complete, pending release.
