### ISSUE TITLE
UDP low-level driver timeout facility lacks a retry mechanism

### ISSUE THREAD

**Issue by GWustenstein** [uhppoted/uhppoted-dll#3]
Background:  In my environment, I have a Raspberry Pi sitting on WiFi acting as a tunnel/relay and controlling node.  Since UHPPOTE packets are UDP and such packets are 'best effort', in a wireless environment packet loss happens quite a bit more often than it does in a wired Ethernet network, about 1 in 2000 appear to get clobbered.  

In Tunnel mode, the vendor's app typically does not notice a missed packet, however it would appear uhppoted-dll (and related modules that leverage the same driver codebase such as uhppoted-codegen) fire off a UDP request packet once then fail if the timeout expires.  This is really noticed when doing an event log database fill or long-duration status polling.

Sure, one can write a wrapper function around the driver, but it seems to me the low-level thingie expecting a response might be better served with --retry [count] parameter or some reasonable default (2, 5?) unless it really is a best effort communique.

Worst case, let's say it's a 2.4ghz WiFi and someone is making popcorn in the microwave...the net is effectively down for 3min, having the two knobs of timeout and retries, one can balance failure response against recovery time given the scenario.

**Comment by uhppoted** [comment]
It was actually a deliberate design decision - there are many, many reasons a UDP packet might get lost (simply dropped by network, service shutdown, network failure, board crash, etc, etc) and any recovery is pretty much application specific.

Timeouts and retries can actually complicate system state and recovery e.g. some light reading:

- [What is Backoff For?](https://brooker.co.za/blog/2022/08/11/backoff.html)
- [Metastability and Distributed Systems](https://brooker.co.za/blog/2021/05/24/metastable.html)
- [The properties of crash-only software](https://brooker.co.za/blog/2012/01/22/crash-only.html)

To address _events_ specifically - _events_ are going to get lost and for robust event logging it's a good idea to supplement the _event listener_ with a script that periodically uses `get-event` to fetch any events that have been received in the interim e.g. there's a sample in the [cookbook](https://github.com/uhppoted/uhppoted/tree/master/cookbook/get-events) of how to store them in a _sqlite3_ DB.

**Comment by uhppoted** [comment]
'k, having mulled this over and thought about it a fair bit - I think they way to do this is with an RPC-like mechanism. Which ... is on the roadmap but not in the near future so don't hold your breath :-).

Am going to close this but will post an update here when that project gets started.

**Comment by GWustenstein** [comment]
I did a deep-dive on the readings, coinciding with some experimental development.  Refactored to a mechanism where state was stored in the db.  Now to the point where the system is robust to random crashes, set breakpoints here and there, ^c at random intervals, etc.  The nice thing about doing this is now I can fix bugs on the fly and things will pick up where it left off, so thank you for the backgrounder!

For data latency and performance reasons, I left a single retry in place; Fine tuning time timeout vs. polling loop to arrive at a decent response time to forward alarm conditions such as Door Force and alarm contact inputs as expeditiously as possible.  Response time of the device is *usually* fast, there are times the device is busy (would certainly like to know what the hell it's CPU board doing during those periods, hello Huawai?) or the packet is lost for good.  

Testing over the last week with a 1s timeout, 1 retry, 10s polling window appears to keep it out of the realm of missing a poll window and feels close to real-time.  This Pi has 5ghz WiFi, so it doesn't suffer the 'popcorn in the microwave' issue of the earlier models, but the system survives pulling the network cable for hours at a time (alarm forwarding be damned!), crashes, restarts, and goes right back to backfilling the db when back up.

**Comment by uhppoted** [comment]
Building rock-solid robust systems is just endlessly fascinating and almost never simple :-) - but that is sounding pretty solid! Nice!
