### ISSUE TITLE
Error in devices.go line 137

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted-dll#7]
Thank you very much for providing the set-door-passcodes. I will try to apply this feature first.

![image](https://github.com/uhppoted/uhppoted-dll/assets/56288040/1c9ff2b7-375e-4dd2-aaea-d2fa9c0520ae)

I suddenly got an error like this in a function that I had created.
can I ask for help with this problem?
what happened so that I can get an error like this?

_Originally posted by @RofiMF in https://github.com/uhppoted/uhppoted-dll/issues/6#issuecomment-1740172717_

**Comment by uhppoted** [comment]
[line 137](https://github.com/uhppoted/uhppoted-dll/blob/main/go/devices.go#L137) in _devices.go_ is this line:

```
...
status.event.timestamp = C.CString(format(response.Event.Timestamp))
...
```

It looks like there is some problem with the timestamp of the latest event - somewhere in your code you have a line like this:
```
      u = uhppoted.Uhppote(uhppote=uhppoted.UHPPOTE(bind, broadcast, listen, timeout, controllers, debug))
```
Can you please set debug to `True` and run it again and attach the output?

**Comment by RofiMF** [comment]
I always set True for debugging, and what appears is like the screenshot I provided

**Comment by uhppoted** [comment]
You should get something like this:
```
GODEBUG=cgocheck=2 && export DYLD_LIBRARY_PATH=../../lib && python3 examples.py  get-status
Namespace(command='get-status', controller=405419896, interlock=1, ip_address='192.168.1.100', subnet_mask='255.255.255.0', gateway_address='192.168.1.5', listener_address='192.168.1.100:60001', card=8000001, card_index=3, door=4, event_index=43, time_profile=29)
 ... sent 64 bytes to 192.168.1.100:60000

 ... request
 ...          00000000  17 20 00 00 78 37 2a 18  00 00 00 00 00 00 00 00  |. ..x7*.........|
 ...          00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 ...          00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 ...          00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 ...          

 ... received 64 bytes from 192.168.1.100:60000
 ... response
 ...          00000000  17 20 00 00 78 37 2a 18  45 00 00 00 02 01 01 01  |. ..x7*.E.......|
 ...          00000010  a1 98 7c 00 20 21 08 10  10 28 32 2c 00 00 00 00  |..|. !...(2,....|
 ...          00000020  00 00 00 00 00 20 04 33  00 00 00 00 00 00 00 00  |..... .3........|
 ...          00000030  00 00 00 23 09 28 00 00  00 00 00 00 00 00 00 00  |...#.(..........|
 ...          
get-status
  ID               405419896
  date/time        2023-09-28 20:04:33
  doors[1]         False
  doors[2]         False
  doors[3]         False
  doors[4]         False
  buttons[1]       False
  buttons[2]       False
  buttons[3]       False
  buttons[4]       False
  relays           0x0
  inputs           0x0
  error            0x0
  info             0
  seq no.          0
  event timestamp  2021-08-10 10:28:32
        index      69
        type       door
        granted    True
        door       1
        direction  in
        card       8165537
        reason     remote open door

```

**Comment by uhppoted** [comment]
Ok, let's do this differently - one of your controllers is returning a flaky response. Can you modify your loop so that it prints out the controller serial number before it executes the _get-status_ call. 

The last one it prints out is probably the one returning the bad response - can you run the examples.py _get-status_ with that controller serial number and _debug_ enabled?

**Comment by RofiMF** [comment]
This is all I got after trying get_status on the problematic S/N controller

![image](https://github.com/uhppoted/uhppoted-dll/assets/56288040/d7b8dc56-e2e5-4b46-9bd5-7902f387a1ed)

**Comment by uhppoted** [comment]
That's all I needed :-) ... thanks! I'll look into it and keep you posted..

**Comment by uhppoted** [comment]
That controller is either fresh out of the box or it's been reset to factory defaults - it doesn't have any events (not even a power-on event) which is unusual and it also has a system error code of 0x83 (131).

It shouldn't crash because of that and I'll have to fix that - but if you want a quick interim workaround then swipe a card so that there is a at least one event in the log.

**Comment by RofiMF** [comment]
I've tried swiping the card but it still keeps getting the same error as before

**Comment by uhppoted** [comment]
Hi,

I've pushed a patch to the `main` branch and it seems to mitigate the issue in my testing:
```
make debug
yapf -ri .
yapf -ri ../../bindings/python
GODEBUG=cgocheck=2 && export DYLD_LIBRARY_PATH=../../lib && python3 examples.py  get-status --controller 303986753
Namespace(command='get-status', controller=303986753, interlock=1, ip_address='192.168.1.100', subnet_mask='255.255.255.0', gateway_address='192.168.1.5', listener_address='192.168.1.100:60001', card=8000001, card_index=3, door=4, event_index=43, time_profile=29)
 ... sent 64 bytes to 192.168.1.100:60000

 ... request
 ...          00000000  17 20 00 00 41 78 1e 12  00 00 00 00 00 00 00 00  |. ..Ax..........|
 ...          00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 ...          00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 ...          00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 ...          

 ... received 64 bytes from 192.168.1.100:60000
 ... response
 ...          00000000  17 20 00 00 41 78 1e 12  00 00 00 00 00 00 00 00  |. ..Ax..........|
 ...          00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 ...          00000020  00 00 00 00 00 19 09 26  00 00 00 00 00 00 00 00  |.......&........|
 ...          00000030  00 00 00 23 09 29 00 00  00 00 00 00 00 00 00 00  |...#.)..........|
 ...          
get-status
  ID               303986753
  date/time        2023-09-29 19:09:26
  doors[1]         False
  doors[2]         False
  doors[3]         False
  doors[4]         False
  buttons[1]       False
  buttons[2]       False
  buttons[3]       False
  buttons[4]       False
  relays           0x0
  inputs           0x0
  error            0x0
  info             0
  seq no.          0
  event timestamp  -
        index      0
        type       none
        granted    False
        door       0
        direction  unknown
        card       0
        reason     
```

(note that the event timestamp is returned as a **blank string** if the event is not valid - the '-' displayed above is implemented with a check inside _examples.py_)

I still need to go through and implement a set of integration tests for this but that shouldn't affect you.

**Comment by RofiMF** [comment]
Thank you for helping resolve this issue, I have implemented what you have fixed and I no longer get the error like yesterday

**Comment by uhppoted** [comment]
Great! Thanks for letting me know :-) .. I'll leave this issue open a little longer while I tidy up the C, C++, etc examples and add a few more tests.

**Comment by RofiMF** [comment]
Hi,
Sorry, do you have a function to check whether the controller is online or not?

**Comment by uhppoted** [comment]
Hi, 

Can you clarify what you mean by online? If you just want to check that a controller is responding then _get-all-controllers_ or _get-controller_ is probably the most convenient function but I'm sure you were aware of that...

**Comment by RofiMF** [comment]
what do you mean by get-device?
I'll try that function if that's what you mean


and do you know the cause of the error I got?

**Comment by uhppoted** [comment]
Ooops, yes, I meant `get-all-devices` and `get-device` (`get-controller` is the command from _examples.py_).

The DLL is responding with _timeout waiting for reply_ because it's discarding the reply it received from the controller which contains an invalid event timestamp: `20c71531316363` - that should be something like e.g. `20231005085332` (for _2023-10-05 08:53:32_).

You might want to do a _get-time_/_set-time_ on that controller to check/set the controller time - if it's up to event #495498 then it's probably been in service for a *long* time.

**Comment by RofiMF** [comment]
How do you solve it so I don't get this error?

**Comment by uhppoted** [comment]
The error is actually in the controller (the event record is either corrupted or just wrong). You'll  have to make your script handle it e.g. you could:

- Try to retrieve an event three times
- If it fails with an error three times then log it as a bad record and add the event index to an _ignore_ list
- Move on to the next event

**Comment by RofiMF** [comment]
okay, I thank you for the advice and all the help

**Comment by uhppoted** [comment]
A pleasure :-)

**Comment by uhppoted** [comment]
Hi,

I'm going to close this out - the underlying cause seems to be fixed and there are now unit and basic integration tests for this error case. Feel free to reopen it if you need to :-).
