### ISSUE TITLE
Example C# Project: Visual Studio for Windows cannot load DLL

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted-dll#9]
### Discussed in https://github.com/uhppoted/uhppoted/discussions/42

<div type='discussions-op-text'>

<sup>Originally posted by **BigMack-1** November 13, 2023</sup>
Hi There,
Just wondering if anyone has a Visual Studio C# example that implements the DLL?

Something that connects to the Board and updates a PIN and\or receives an entry\exit access.

Cheers</div>

<div type='discussions-op-text'>
Just a quick note - I started looking into this and it seems like on Visual Studio for Windows can't import the DLL compiled by Go. No idea why (possibly something to do with the gcc compiler) - I'll have to do some more digging to figure out why and how to fix it.
</div>

**Comment by twystd** [comment]
Working _Visual Studio for Mac_ and _Visual Studio for Windows_ examples added to the _examples/csharp_ folder.
